config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  get 'home/index'
  root 'home#index'
  resources :payments
  resources :paymenttypes
  resources :boards
  resources :environments
  resources :products
  resources :categories

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :paymenttype
end

app/models/paymenttype.rb
class Paymenttype < ActiveRecord::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:numberrequest, :discount, :numbernote, :amount, :paymenttype_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numberrequest %><br>
    <%= f.number_field :numberrequest %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.number_field :discount %>
  </div>
  <div class="field">
    <%= f.label :numbernote %><br>
    <%= f.number_field :numbernote %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :paymenttype_id %><br>
    <%= f.text_field :paymenttype_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th>Numberrequest</th>
      <th>Discount</th>
      <th>Numbernote</th>
      <th>Amount</th>
      <th>Paymenttype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.numberrequest %></td>
        <td><%= payment.discount %></td>
        <td><%= payment.numbernote %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.paymenttype %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numberrequest:</strong>
  <%= @payment.numberrequest %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @payment.discount %>
</p>

<p>
  <strong>Numbernote:</strong>
  <%= @payment.numbernote %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Paymenttype:</strong>
  <%= @payment.paymenttype %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>