config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  get 'home/index'
  root 'home#index'
  resources :payments
  resources :paymenttypes
  resources :boards
  resources :environments
  resources :products
  resources :categories

end

app/models/environment.rb
class Environment < ActiveRecord::Base
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]

  # GET /environments
  # GET /environments.json
  def index
    @environments = Environment.all
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render :show, status: :created, location: @environment }
      else
        format.html { render :new }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      if @environment.update(environment_params)
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :edit }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment.destroy
    respond_to do |format|
      format.html { redirect_to environments_url, notice: 'Environment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:description, :numberboard)
    end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.erb
<%= form_for(@environment) do |f| %>
  <% if @environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% @environment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :numberboard %><br>
    <%= f.number_field :numberboard %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/environments/edit.html.erb
<h1>Editing Environment</h1>

<%= render 'form' %>

<%= link_to 'Show', @environment %> |
<%= link_to 'Back', environments_path %>

app/views/environments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Environments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Numberboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @environments.each do |environment| %>
      <tr>
        <td><%= environment.description %></td>
        <td><%= environment.numberboard %></td>
        <td><%= link_to 'Show', environment %></td>
        <td><%= link_to 'Edit', edit_environment_path(environment) %></td>
        <td><%= link_to 'Destroy', environment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Environment', new_environment_path %>

app/views/environments/new.html.erb
<h1>New Environment</h1>

<%= render 'form' %>

<%= link_to 'Back', environments_path %>

app/views/environments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @environment.description %>
</p>

<p>
  <strong>Numberboard:</strong>
  <%= @environment.numberboard %>
</p>

<%= link_to 'Edit', edit_environment_path(@environment) %> |
<%= link_to 'Back', environments_path %>